- pages/adminLogin.tsx
> 어드민 로그인 페이지 수정

- pages/info/history.tsx
- pages/info/task.tsx
- pages/info/vision/index.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/HeaderMenu.tsx
- src/components/Layout.tsx
- src/components/Sidebar.tsx
- src/components/SidebarMenu.tsx
> Ly 35 history

- next.config.js
- pages/info/index.tsx
> LY-30 <센터장 소개 페이지>

- next.config.js
- pages/info/index.tsx
- pages/info/vision/index.tsx
> Ly 46 센터 비전 페이지

- pages/info/vision/purpose.tsx
- tailwind.config.js
> LY-47 설립 목적 페이지

- pages/data/index.tsx
- pages/data/study.tsx
> Ly 28 논문 및 연구 보고서

- pages/info/organization/analytics.tsx
- pages/info/organization/ethics.tsx
- pages/info/organization/network.tsx
- pages/info/organization/research.tsx
> LY-50-센터조직 페이지 수정

- pages/research/index.tsx
- src/components/ResearchCard.tsx
pull 안한 것 때문에 '브랜치 ver1'  '브랜치 ver2'를 만들었습니다.
이번엔 pull 해서 다시 올립니다
> Ly 49 ver.2 연구 및 사업 페이지

- pages/info/index.tsx
- pages/info/task.tsx
> Ly 57 ver1 센터장 소개 페이지 수정

- pages/major/alumni.tsx
- src/components/NameCard.tsx
> Ly 55 동문 페이지

- pages/major/vision.tsx
- src/styles/styles.module.css
> LY-87 졸업 후 진로페이지 반응형

- pages/info/index.tsx
- pages/major/measurement.tsx
- src/components/info/CenterLeaderCareer.tsx
- src/components/info/CenterLeaderEducation.tsx
- src/components/info/CenterLeaderHistory.tsx
- src/components/info/CenterLeaderInfo.tsx
> LY-74 <wow>

- pages/info/index.tsx
- pages/info/vision.tsx
- pages/major/measurement.tsx
- src/components/info/CenterLeaderCareer.tsx
- src/components/info/CenterLeaderEducation.tsx
- src/components/info/CenterLeaderHistory.tsx
- src/components/info/CenterLeaderInfo.tsx
> Ly 76 센터비전 반응형

- pages/info/index.tsx
- pages/info/vision.tsx
- pages/major/measurement.tsx
- src/components/info/CenterLeaderCareer.tsx
- src/components/info/CenterLeaderEducation.tsx
- src/components/info/CenterLeaderHistory.tsx
- src/components/info/CenterLeaderInfo.tsx
- src/components/info/MemberTableBody.tsx
- src/components/info/MemberTableHeader.tsx
MemberTableBody 38번째 줄에 글자를 줄바꿈? 해주는 break-all 이라는 키워드랑
MemberTableHeader 에서 기존 wide 비율은 xs(480px) 로 넘기고 기본 비율을 수정했습니다
> Ly 96 연구협력 네트워크 연구 자문단 연구 윤리 자문단 반응형

- package-lock.json
- package.json
- src/components/info/NameCard.tsx
- typing.d.ts
> Ly 95 namecard 반응형

- src/components/data/MaterialTableBody.tsx
- src/components/data/MaterialTableToggle.tsx
- src/components/notice/NewsTableToggle.tsx
- 날짜 입력 기본값(실제저장값: moment.format() -> 보여주는값: substring으로 제어)
- 파일 수정 버튼 구현
> LY-103-날짜파일추가수정

- pages/major/vision.tsx
- src/components/data/MaterialTableBody.tsx
- src/components/data/MaterialTableToggle.tsx
- src/components/notice/NewsTableToggle.tsx
- text title 하단 border 추가
- 글자 크기 수정(0.925rem)
> Ly 104 졸업후진로페이지 반응형 추가 수정

- pages/info/vision.tsx
- src/components/info/CenterLeaderInfo.tsx
- src/components/info/MemberTableBody.tsx
- src/components/info/MemberTableButton.tsx
- src/components/info/MemberTableHeader.tsx
- src/components/major/MajorForm.tsx
LY-74 : 배너부분 비율에 따라 반응하도록 수정 
센터로고는 모바일 버전에서는 안 보이도록 수정
LY-75 : w-[100%]로 수정
LY-76 : 모바일 버전에서는 이메일 안 보이도록 수정
'수정'버튼은 lg 사이즈부터 보이도록 수정
LY-96 : 배너부분 비율에 따라 반응하도록 수정
> LY-105 <message>

- pages/notice/[pid].tsx
- src/components/data/MaterialTable.tsx
- src/components/data/MaterialTableBody.tsx
- src/components/data/MaterialTableButton.tsx
- src/components/data/MaterialTableHeader.tsx
- src/components/data/MaterialTableToggle.tsx
- src/components/notice/NewsTable.tsx
- src/components/notice/NewsTableBody.tsx
- src/components/notice/NewsTableButton.tsx
- src/components/notice/NewsTableHeader.tsx
- src/components/notice/NewsTableToggle.tsx
- src/utils/Utils.ts
- typing.d.ts
- merge conflict resolved
- dynamic routes (새로고침 문제는 아직 해결 못했습니다.)
- date => createdAt
- 반응형
> merge_Resolved

- src/components/main/MainForum.tsx
> LY-130-메인포럼레이아웃수정

- pages/notice/[pid].tsx
- src/components/common/Layout/Layout.tsx
- src/components/data/MaterialTableBody.tsx
- src/components/data/MaterialTableToggle.tsx
- src/components/main/MainNewsRecruit.tsx
- src/components/main/NewsCard.tsx
- src/components/notice/NewsTableBody.tsx
- src/components/notice/NewsTableToggle.tsx
- 맥북 Safari 메인페이지 레이아웃 수정
src/components/main/MainNewsRecruit.tsx
src/components/main/NewsCard.tsx
우선 급한대로 수정했습니다,,,
> Ly 133 mac safari mainpage
